BEGIN;

ALTER TABLE public.entregas
  ADD COLUMN IF NOT EXISTS ruta_geojson JSONB,
  ADD COLUMN IF NOT EXISTS ruta_distancia_metros INTEGER,
  ADD COLUMN IF NOT EXISTS ruta_duracion_segundos INTEGER,
  ADD COLUMN IF NOT EXISTS ruta_generada_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ruta_destino_latitud DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS ruta_destino_longitud DOUBLE PRECISION;

COMMIT;
